### ISSUE TITLE
vscode auto format case err

### ISSUE THREAD

**Issue by czyt** [teocloud/teo-vscode#2]
when enable auto format  in vscode,the `schema.teo` may be formatted in wrong.

**Comment by czyt** [comment]
I found a solution,in your vscode setting.json add the below
```json
"[teo]": {
		"editor.defaultFormatter": "yeannylam.teo-vscode",
		"editor.formatOnSave": false
	},
```

**Comment by victorteokw** [comment]
Hi @czyt, noted. The formatter actually is unfinished. I will temporarily disable it.
